-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    id integer NOT NULL DEFAULT 'nextval('usuarios_id_seq'::regclass)',
    usuario character varying(100) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default",
    pass character varying(200) COLLATE pg_catalog."default",
    create_time timestamp without time zone DEFAULT 'now()',
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);
END;